---
- hosts: all
  tasks:
    - name: creating backup file
      shell: tar cfz /tmp/html.{{ ansible_date_time.date }}.tar.gz  /var/www/html
      become: yes
    - name: Specifying a destination path
      fetch:
        src: /tmp/html.{{ ansible_date_time.date }}.tar.gz
        dest: /home/ubuntu/backup/{{ inventory_hostname }}/
        flat: yes