---
- hosts: all
  tasks:
    - name: Specifying a destination path
      synchronize:  src={{ item }} dest=/home/ubuntu/backup/{{ ansible_date_time }}/{{ inventory_hostname }}/ mode=pull
        with_items:
          - "/var/www/html"
