---
- hosts: all
  tasks:
    - name: creating backup file
      shell: tar cfz /tmp/html.{{ ansible_date_time }}.tar.gz  /var/www/html
      register: files_to_copy
    - name: Specifying a destination path
      fetch:
        src: /tmp/html.{{ ansible_date_time }}.tar.gz
        dest: /home/ubuntu/backup/{{ ansible_date_time }}/{{ inventory_hostname }}/
        flat: yes