---
- hosts: all
  tasks:
    - name: creating backup file
      shell: tar cfz /tmp/html.tar.gz  /var/www/html
      become: yes
    - name: Specifying a destination path
      fetch:
        src: /tmp/html.tar.gz
        dest: /home/ubuntu/backup/{{ ansible_date_time }}/{{ inventory_hostname }}/
        flat: yes