---
  - name: Terminate EC2 Instance
    hosts: localhost
    connection: local
    gather_facts: False
    tags: provisioning
    vars:
      instance_type: t2.micro
      security_group: webservers
      image: ami-0b44050b2d893d5f7
      region: ap-south-1
      keypair: devops
      count: 1
    tasks:
      - name: Terminate
        ec2_instance:
          state: absent
          region: ap-south-1
          filters:
            tag:Name: Web Server